version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: ativa_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ativa_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ativa_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ativa_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ativa_db
      - SECRET_KEY=supersecretkey
    networks:
      - ativa_network

  frontend:
    build: ./frontend
    container_name: ativa_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - ativa_network

networks:
  ativa_network:
    driver: bridge

volumes:
  postgres_data:
